### PR TITLE
Change in translations folder in 0.111

### PR DESCRIPTION
**Pull request by kuchel77**
healthchecksio: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this

This is the error message from HA 0.109.1. All this does is move the folder.

### CODE REVIEW

**Comment by ludeeus** [comment]
This change will break it for anyone that is no < 0.109.
It's better to just do a copy and have both directories, at least for a while.

Can you update this PR with that?

**Comment by kuchel77** [comment]
Hopefully there is a copy of both directories there know. It was more just as a heads up for others with translations in HACS that things are changing and could break if not updated for 0.111. Will the HA code still complain if both are there?

**Comment by ludeeus** [comment]
I'm fully aware of this change in HA, it was me that added it 🙈

**Comment by kuchel77** [comment]
I'll just sit here mainsplaining it to you then....

**Pull request merged**
